apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jeff-dotnet60
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jeff-dotnet60
    app.kubernetes.io/part-of: jeff-dev-samples
  name: jeff-dotnet60
  namespace: jephilli
spec:
  port:
    targetPort: 8081
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: jeff-dotnet60
    weight: 100
status: {}
