apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: jeff-go
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: jeff-go
    app.kubernetes.io/part-of: jeff-dev-samples
  name: jeff-go
  namespace: jephilli
spec:
  ports:
  - port: 8081
    targetPort: 8081
  selector:
    app.kubernetes.io/instance: jeff-go
status:
  loadBalancer: {}
