apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-jeff
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-jeff
    app.kubernetes.io/part-of: jeff-dev-samples
  name: nodejs-jeff
  namespace: jephilli
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/instance: nodejs-jeff
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app.kubernetes.io/instance: nodejs-jeff
    spec:
      containers:
      - image: quay.io/redhat-appstudio/user-workload:jephilli-nodejs-jeff
        imagePullPolicy: Always
        livenessProbe:
          httpGet:
            path: /
            port: 3001
          initialDelaySeconds: 10
          periodSeconds: 10
        name: container-image
        ports:
        - containerPort: 3001
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 10
          tcpSocket:
            port: 3001
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
