apiVersion: route.openshift.io/v1
kind: Route
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: nodejs-jeff
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: nodejs-jeff
    app.kubernetes.io/part-of: jeff-dev-samples
  name: nodejs-jeff
  namespace: jephilli
spec:
  port:
    targetPort: 3001
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: nodejs-jeff
    weight: 100
status: {}
